### PR TITLE
Inclusion of a new set of xml files compatible with the updated L1 menu for Run 3

### PR DESCRIPTION
**Pull request by elfontan**
A full set of xml files for the L1 emulation of prescales and masks coherent with the updated L1 menu for Run 3 has been created. The current version of the updated L1 Menu can be found in [1]: _L1Menu_Collisions2022_v0_1_5_.
In the context of the trigger studies for the preparation of the Run 3 menu (L1+HLT), we recently faced an issue related to the emulation of the L1 prescales. Two different issues were found out:
- format of the PS table (some documentation and a recipe can be found [here](https://github.com/cms-l1-dpg/L1MenuRun3/tree/master/preliminary/L1Menu_Collisions2022_v0_1_5/PrescaleTable));
- usage of the fractional PS ([PR#37046](https://github.com/cms-sw/cmssw/pull/37046)).

Once that these new files are available here, a PR to update the [PrescalesVetosFract_cff.py](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/python/PrescalesVetosFract_cff.py) file will be prepared.

[1]
https://github.com/cms-l1-dpg/L1MenuRun3/tree/master/preliminary/L1Menu_Collisions2022_v0_1_5

### CODE REVIEW

**Comment by elfontan** [comment]
The PR has been updated including a set of files compatible with an updated version of the L1 menu: _L1Menu_Collisions2022_v0_1_6_.
The corresponding tag in condDB can be found [here](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_Collisions2022_v0_1_6_xml): _L1Menu_Collisions2022_v0_1_6_xml_.

**Comment by epalencia** [comment]
Please test

**Comment by epalencia** [comment]
+l1

**Comment by smuzaffar** [comment]
@[elfontan](https://github.com/elfontan) these are all new data files. Is there any cms-sw/cmssw pull request which uses these files?

**Comment by elfontan** [comment]
Dear @smuzaffar, 
the CMSSW PR that uses these files would be this one:
https://github.com/cms-sw/cmssw/pull/37138.
It is still a draft PR because I wanted to wait for these files available here before proceeding.

**Comment by smuzaffar** [comment]
thanks @elfontan but looks like non of the PR tests are actually using the new files otherwise PR tests for httpshttps://github.com/cms-sw/cmssw/pull/37138 should have failed. Are there any `runTheMatrix.py` workflows which actually use these files?

**Comment by elfontan** [comment]
Dear @smuzaffar,
sorry for my late reply!
You are right, the new files are not used in any standard workflow. 
They would be used for the re-emulation of the L1 prescales and masks when applying a dedicated recipe that you can find e.g. [here](https://github.com/cms-l1-dpg/L1MenuRun3/blob/master/preliminary/L1Menu_Collisions2022_v0_1_6/PrescaleTable/README.md). The specific script that calls those two configuration files containing the new files is [hackConditions_cff.py](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/python/hackConditions_cff.py#L33-L34).

We would like to have these files updated just for clarity and coherence with what we are going to use (in terms of menu and prescales) as default for Run 3. (Most likely these files will be updated again by the end of the month, so we can also consider to postpone this point - but having it clarified by the preparation of CMSSW_12_3_0).
Please let me know if something is unclear and how we can eventually handle the validation in this kind of situations, if it is needed.

Cheers,
--Elisa

**Comment by smuzaffar** [comment]
+externals

sounds good @elfontan . I am merging this now and these new files should be available in next CMSSW_12_4_X IB . If you need to get these files back ported to 12.3.X then please open a github issue for cms-sw/cmssw repository

**Comment by elfontan** [comment]
Hello @smuzaffar,
thank you, also for precising about the need of a backport to have them in CMSSW_12_3_X. 
I will probably open a github issue for this, unless we expect a update of these files very quickly, and in this case I will update these files and ask you for the backport only once (by the timeline of CMSSW_12_3_0, deadline Apr 8).

Cheers,
--Elisa

**Pull request merged**
