### PR TITLE
Updated files for the v1_0_0 menu for Run 3 

### PR DESCRIPTION
**Pull request by elfontan**
An updated full set of xml files for the L1 emulation of prescales and masks coherent with the updated v1_0_0 L1 menu for Run 3 is provided, targeting **CMSSW_12_3_0**. 
The current version of the updated L1 Menu can be found in [1]: _L1Menu_Collisions2022_v1_0_0_.
(Previous reference PR https://github.com/cms-data/L1Trigger-L1TGlobal/pull/8)

In the context of the trigger studies for the preparation of the Run 3 menu (L1+HLT), we recently faced an issue related to the emulation of the L1 prescales. Two different issues were found out:
- format of the PS table (some documentation and a recipe can be found [here](https://github.com/cms-l1-dpg/L1MenuRun3/tree/master/development/L1Menu_Collisions2022_v1_0_0/PrescaleTable));
- usage of the fractional PS (https://github.com/cms-sw/cmssw/pull/37046).

Once that these new files are available here, we will follow-up with the PR to update the [PrescalesVetosFract_cff.py](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/python/PrescalesVetosFract_cff.py) file: https://github.com/cms-sw/cmssw/pull/37453.

[1]
https://github.com/cms-l1-dpg/L1MenuRun3/tree/master/development/L1Menu_Collisions2022_v1_0_0

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by epalencia** [comment]
+l1

**Comment by epalencia** [comment]
@smuzaffar , could you please review?

**Comment by smuzaffar** [comment]
+externals
@epalencia , this looks good to me. If I understand correctly, this is needed for https://github.com/cms-sw/cmssw/pull/37453  ... right? I already have started the tests for https://github.com/cms-sw/cmssw/pull/37453 . So this data pr can be merged once  https://github.com/cms-sw/cmssw/pull/37453 is ready to go in.

**Comment by elfontan** [comment]
Hi @smuzaffar, yes, correct. These are the "default files" to be used in those config files, that, as we discussed last time, are not used in any standard workflow. 
They would be used for the re-emulation of the L1 prescales and masks when applying a dedicated recipe that you can find e.g. [here](https://github.com/cms-l1-dpg/L1MenuRun3/blob/master/preliminary/L1Menu_Collisions2022_v0_1_6/PrescaleTable/README.md). The specific script that calls those two configuration files containing the new files is [hackConditions_cff.py](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/python/hackConditions_cff.py#L33-L34). 

I have another question.
I opened the github issue #10 for the backport to CMSSW_12_3_0: do we need this PR merged to proceed there?

**Comment by perrotta** [comment]
@elfontan I notice that besides updating the files, you are also renaming them here with the new Run3 L1 menu name.
Can you confirm that you did check that the previous filenames will not be searched for anywhere else in CMSSW or in the online version of it once the sibling #37453 PR is merged?

**Comment by elfontan** [comment]
Dear @perrotta,
I "innocently" did it just for additional clarity.
I confirm that I checked that the previous files are not searched for anywhere else in CMSSW except for the two config files updated in PR#37453.
However, I do not even understand what it means "in the online version of it"...
What should I check precisely?

Thanks a lot in advance,
--Elisa

**Comment by perrotta** [comment]
+1
- tested with #37453

**Comment by elfontan** [comment]
Thank you!
I opened the related github issue for the backport https://github.com/cms-data/L1Trigger-L1TGlobal/issues/10, let me know if it is enough, @smuzaffar.
Cheers,
--Elisa

**Pull request merged**
