### PR TITLE
Updated files for the v1_1_0 menu for Run 3 (and minor fix for v1_0_0)

### PR DESCRIPTION
**Pull request by elfontan**
An updated full set of xml files for the L1 emulation of prescales and masks coherent with the updated v1_1_0 L1 menu for Run 3 is provided, targeting **CMSSW_12_4_0**. 
The current version of the updated L1 Menu can be found in [1]: _L1Menu_Collisions2022_v1_1_0_.
**NOTE**: the current setup of the L1 prescales is still not updated according to the needs for the start of Run 3 given some ongoing discussions to finalize them. For now, the PS table is pretty much the copy of the last 2018 PS table. The update of these files is needed in order to provide a structure of the PS and masks tables fully compatible with the updated menu, so that it is usable for development purposes. 

A minor update of the files from the previous PR https://github.com/cms-data/L1Trigger-L1TGlobal/pull/9) is also included.

In the context of the trigger studies for the preparation of the Run 3 menu (L1+HLT), we faced an issue related to the emulation of the L1 prescales. Two different issues were found out:
- format of the PS table (some documentation and a recipe can be found [here](https://github.com/cms-l1-dpg/L1MenuRun3/tree/master/development/L1Menu_Collisions2022_v1_1_0/PrescaleTable));
- usage of the fractional PS (https://github.com/cms-sw/cmssw/pull/37046).

Once that these new files are available here, we will follow-up with the draft PR to update the [PrescalesVetosFract_cff.py](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/python/PrescalesVetosFract_cff.py) file: https://github.com/cms-sw/cmssw/pull/38250.

Related github issue for the backport to CMSSW_12_4_0 is https://github.com/cms-data/L1Trigger-L1TGlobal/issues/12.

[1]
https://github.com/cms-l1-dpg/L1MenuRun3/tree/master/development/L1Menu_Collisions2022_v1_1_0

### CODE REVIEW

**Comment by epalencia** [comment]
please test

**Comment by epalencia** [comment]
Please test

**Comment by elfontan** [comment]
Hello @smuzaffar,
do you understand the failure above during the test? Any hint about it?
Thanks a lot in advance,
--Elisa

**Comment by smuzaffar** [comment]
> Hello @smuzaffar, do you understand the failure above during the test? Any hint about it? Thanks a lot in advance, --Elisa

I guess tests were running on a busy machine as I see error message
```
----- Begin Fatal Exception 06-Jun-2022 01:12:18 CEST-----------------------
An exception of category 'ExternalFailed' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module ExternalGeneratorFilter/'toTest'
Exception Message:
failed waiting for external process 22444_0. Timed out after 300 seconds.
----- End Fatal Exception -------------------------------------------------
```
anyway, tests are running fine now. By the way, is there any cmssw PR to test these data file changes?

**Comment by elfontan** [comment]
Thank you @smuzaffar!
The related cmssw PR is https://github.com/cms-sw/cmssw/pull/38250.
However, as mentioned in the previous similar PR, these are the "default files" to be used in some config files, that are not used in any standard workflow. 
They would be used for the re-emulation of the L1 prescales and masks when applying a dedicated recipe that you can find e.g. [here](https://github.com/cms-l1-dpg/L1MenuRun3/blob/master/development/L1Menu_Collisions2022_v1_1_0/PrescaleTable/README.md). The specific script that calls those two configuration files containing the new files is [hackConditions_cff.py](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/python/hackConditions_cff.py#L33-L34).

**Comment by smuzaffar** [comment]
+externals

**Comment by cecilecaillol** [comment]
+l1

**Comment by elfontan** [comment]
Hello,
I just moved https://github.com/cms-sw/cmssw/pull/38250 from "Draft" to "Ready for review" and I am going to prepare the related backport. Would it be possible to proceed with the integration of these files and to deal with the related open issue https://github.com/cms-data/L1Trigger-L1TGlobal/issues/12 for the backport?

Thanks a lot in advance,
--Elisa

**Comment by perrotta** [comment]
+1
- See https://github.com/cms-sw/cmssw/pull/38250#issuecomment-1153147772

**Pull request merged**
