### PR TITLE
input files for unit test of `L1TGlobalProducer`

### PR DESCRIPTION
**Pull request by missirol**
Input files required for the new unit test introduced in https://github.com/cms-sw/cmssw/pull/39832.

Attn: @elfontan

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
  - pull_requests = https://github.com/cms-sw/cmssw/pull/39832

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Comment by missirol** [comment]
@perrotta @rappoccio

We are missing a signature here, and this cms-data PR needs (well, needed) to be merged before https://github.com/cms-sw/cmssw/pull/39832 . I guess it will still be okay if this is done before the next IB is built.

By the way, since the actual L1T bugfix (https://github.com/cms-sw/cmssw/pull/39464) is yet to be backported to 12_5_X, I would backport "https://github.com/cms-sw/cmssw/pull/39464 + https://github.com/cms-sw/cmssw/pull/39832" together, unless there are objections from ORP or L1T (@cecilecaillol , @epalencia). If so, this `cms-data` update needs to be backported to 12_5_X in `cmsdist`.

**Comment by perrotta** [comment]
merge

**Pull request merged**
