### PR TITLE
New L1T prescales table that cover all 512 algorithms

### PR DESCRIPTION
**Pull request by rekovic**
Please merge this ASAP.

The new L1T prescales table covering all 512 algorithms is 
needed for accessing L1T prescales, and PR 80x #16966 and 90x #16967.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@rekovic , do you need both L1Menu_HeavyIons2016_v1.xml and L1?Menu_HeavyIons2016_v1.1.xml files

**Comment by rekovic** [comment]
> @rekovic , do you need both L1Menu_HeavyIons2016_v1.xml and L1?Menu_HeavyIons2016_v1.1.xml files

@smuzaffar Thanks. 
Sure, these were used at some point at P5, so we might as well add them.
But the most important is the Luminosity/startup/UGT_BASE_RS_PRESCALES_v11.xml.

**Comment by davidlange6** [comment]
don’t we have these in the DB already?

**Comment by rekovic** [comment]
@davidlange6 We should.

**Comment by davidlange6** [comment]
so we don’t need (or want) to duplicate the DB in CMSSW..  you can’t use them straight from the DB?

**Comment by rekovic** [comment]
OK then not to merge data 1Menu_HeavyIons2016's.
The important one is the Luminosity/startup/UGT_BASE_RS_PRESCALES_v11.xml.

**Comment by smuzaffar** [comment]
@rekovic , I have created #7 which only contain Luminosity/startup/UGT_BASE_RS_PRESCALES_v11.xml.

**Comment by rekovic** [comment]
@smuzaffar Thanks!  I just realised that I should have done this, otherwise you could not stop the L1T Menu files from being merged.  Thanks.

**Comment by smuzaffar** [comment]
@rekovic , you have this  Luminosity/startup/UGT_BASE_RS_PRESCALES_v11.xml part of https://github.com/cms-sw/cmssw/pull/16967/files#diff-70ffc084a8a6963a82eb259963b071f2 i.e. #19967. I guess you need to remove it from CMSSW once it is available via external data

**Comment by rekovic** [comment]
Thanks. I guess I should do it later today already ?

**Comment by smuzaffar** [comment]
yes you can do it based on today's 11h00 90X IB (where this data external should be available).

**Comment by rekovic** [comment]
done.  https://github.com/cms-sw/cmssw/pull/17016.

**Pull request closed without merging**
